Automattic/i18n-calypso

package.json

For the Calypso React 15 upgrade, i.e. https://github.com/Automattic/wp-calypso/pull/5116#issuecomment-225642078
cc @blowery @Tug

package.json: Bump interpolate-components to 1.0.5

---

test/index.js

Use renderToStaticMarkup to avoid `react-dataroot` attribute being added,
and take into account that React 15 doesn't auto-add `<span>`s around text
anymore, see https://facebook.github.io/react/blog/2016/04/07/react-v15.html#no-more-extra-ltspangts
This is basically Automattic/wp-calypso@b14809a
which seems to have been lost when moving i18n-calypso to its own repo.
cc @Tug for review

Tests: Update for React 15

---

package.json

Which is the first version to use Babel 6.
Needs #4 to be merged first.
cc @Tug for review

Bump interpolate-components to 1.1.0

---

lib/index.js
package.json

See https://github.com/Automattic/wp-calypso/pull/6121. I guess we need to release 1.3.1 with this fix. :-/
cc @gwwar @Tug

Fix TypeError: `interpolateComponents is not a function`

---

cli/formatters/pot.js
test/cli/index.js
test/cli/pot.pot

A standard PO file header has each line of the header ending by a printed `\n`, see http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html#sec-poheader
This adds those and in the tests accordingly.

Add verbatim line breaks to the PO header

---

cli/formatters/php.js
cli/formatters/pot.js
cli/index.js
cli/preprocess-xgettextjs-match.js
test/cli/examples/i18n-test-examples.jsx
test/cli/index.js
test/cli/pot.pot
test/data/index.js
test/index.js

The [`pot.pot`](https://github.com/Automattic/i18n-calypso/pull/12/files#diff-7458440ce119e7b6ea3c3c9315e79f46) has an example, it now includes entries like:
```
#: test/cli/out/i18n-test-examples.js:6
msgid "My hat has three corners."
msgstr ""
```
The PHP output now looks like this:
```
__( "My hat has three corners." ), // test/cli/out/i18n-test-examples.js:6
```

Include locations of the strings in the output

---

cli/formatters/pot.js
cli/index.js
cli/preprocess-xgettextjs-match.js
package.json
test/cli/examples/i18n-test-examples.jsx
test/cli/index.js
test/cli/pot.pot

This enables parsing of [babylon parser output](https://www.npmjs.com/package/babylon#output) which comes through https://github.com/Automattic/xgettext-js/pull/11.
The main changes that need accomodation:
- `Literal` is split into subliterals of which we are only interested in `StringLiteral`
- the `raw` property was moved into `extra.raw`
- we need to also check for `StringLiteral` in an `innerProp`
This is in order to make https://github.com/Automattic/wp-calypso/pull/7152 possible.

Enable POT generation from the Calypso source

---

index.js
lib/index.js
test/data/index.js
test/index.js

This introduces `addTranslations()` which takes a translations object and adds it do the existing one. Fixes #8

Allow adding translations to an existing jed object

---

CHANGELOG.md
cli/formatters/pot.js
package.json
test/cli/index.js
test/cli/pot.pot

Currently line breaks within strings lead to invalid POT files:
```
#: wp-calypso/client/my-sites/exporter/guided-transfer-details.jsx:28
msgid ""
"Have one of our Happiness Engineers {{strong}}transfer your
site{{/strong}} "
"to a self-hosted WordPress.org installation with
one of our hosting partners."
msgstr ""
```
This changes the output to:
```
#: wp-calypso/client/my-sites/exporter/guided-transfer-details.jsx:28
msgid ""
"Have one of our Happiness Engineers {{strong}}transfer your\nsite{{/strong}} "
"to a self-hosted WordPress.org installation with\none of our hosting "
"partners."
msgstr ""
```
It also handles this case:
```
#: wp-calypso/client/me/help/help-unverified-warning/index.jsx:37
msgid ""
"Trouble activating your account?\\
Just click this button and we'll "
"resend the …
```

Fix POT rendering of line breaks

---

bin/index.js
package.json

This adds support for star patterns in the input filenames for the CLI.
You can now write:
```
i18n-calypso -i src/**/*.js -o output.pot
```
And it will scan your `src` folder recursively and look for all `.js` files.

Add support for glob in inputFiles

---

lib/index.js
package.json

`lru-cache` has as a dependency `pseudomap`, which has many outstanding PRs.
Specifically, https://github.com/isaacs/pseudomap/pull/6 preventing webpack2 processing it.
* Include `i18n-calypso` in a webpack2 project, such as Delphin:
package json:
```json
"i18n-calypso": "Automattic/i18n-calypso#update\/lru-implementation",
```
* build, in delphin `npm run start:static`, validate it succeeds
previously we would get:
```
SyntaxError: Unexpected token: punc (:) [bundle.cbeb532adbd6bab9833b.js:84105,13]
```
* Assert all tests pass
@Automattic/sdev-feed

Replace LRU cache implementation

---

lib/localize/index.js

Sometimes it's necessary to call a function on a React instance during testing. But when `localize()` wraps the component, it's impossible to access to the actual component.
E.g.
```js
const MyComponent = React.createClass( {
sayMyName() {
var s = new SpeechSynthesisUtterance();
s.text = 'Heisenberg';
s.lang = 'en-US';
speechSynthesis.speak( s );
}
} );
export default localize( MyComponent );
```
and
```js
const = component = TestUtils.renderIntoDocument( <MyComponent { ...props } /> );
component.sayMyName();
```
Will throw.

Allow exposed composed component

---

lib/localize/index.js
test/localize.js

The display name of Localize component is currently Localize+ComponentName which is not consistent with react-redux HOC connect which is Connect(ComponentName).
This convension makes it easier to identify Localize as HOC when using tools such as Rect Perf or Rect DevTools.

Change Localize HOC display name to be consistent with react-redux

---

CHANGELOG.md
package.json
test/index.js

This pull request simply makes sure we use the latest version of the [`moment-timezone` module](https://www.npmjs.com/package/moment-timezone), i.e. version `0.5.11` (see the [changelog](https://github.com/moment/moment-timezone/blob/master/changelog.md) for the list of changes since version `0.4.0`).
1. Run `git checkout update/moment-timezone`
2. Run `npm install`
3. Run `npm test` and check that no unit test fails

Update moment-timezone to latest available version

---

bin/index.js

The `keywords` option is supported by [the cli](https://github.com/Automattic/i18n-calypso/blob/master/cli/index.js#L20), but there is no way to use it through the cli options, it should be enabled.
Simple usage
```bash
$ i18n-calypso -o ./outputFile.pot -i ./inputFile.js -k translate,t
```

Cli: enable keywords option

---

bin/index.js
package.json

It's already possible to use `glob` patterns ([node-glob](https://github.com/isaacs/node-glob)) to specify files to generate translations for, but that support was insufficient. As seen in the `wp-calypso` Makefile ([here](https://github.com/Automattic/wp-calypso/blob/master/Makefile#L195)), the command is being invoked with a list of plain paths (the result of a complex `find` command).
To remove that `find` command and use file patterns, we need to switch to [globby](https://github.com/sindresorhus/globby), a more advanced version of `glob` that supports negative patterns, like this:
`i18n-calypso **/*.js **/*.jsx !excluded_dir/**`
I also removed references to `process.env.PWD` since they don't work on Windows. Does it matter to use `process.cwd()` instead? (Which is used by default). I …

Added support for input file patterns in the CLI script

---

cli/preprocess-xgettextjs-match.js
test/cli/examples/i18n-test-examples.jsx
test/cli/index.js

This prevents the options object from being ignored with the "new" plural syntax.
Example string:
```
this.translate(
'Registering this domain for a company? + Add Organization Name',
'Registering these domains for a company? + Add Organization Name',
{
context: 'Domain contact information page',
comment: 'Count specifies the number of domain registrations',
count: 5
}
```
Without this patch, the context and comment are ignored in the output.

Handle options with new plural syntax

---

test/cli/index.js

This PR adds a test to ensure that string templates are handled correctly in the PHP format.
@akirk: I think the different levels of escaping in the PHP and POT tests is correct, but it still looks a bit weird.  Can I get a second opinion, please?

Add PHP template literal test

---

cli/formatters/pot.js
test/cli/index.js

Currently, the program crashes when encountered a very long line without seperators.
For example, give this input:
```js
translate('LoremipsumdolorsitametconsecteturadipiscingelitseddoeiusmodtemporincididuntutlaboreetdoloremagnaaliquaUtenimadminimveniamquisnostrudexercitationullamcolaborisnisiutaliquipexeacommodoconsequat.')
``` 
The recursive function [`#multiline`](https://github.com/Automattic/i18n-calypso/blob/master/cli/formatters/pot.js#L59) can't identify any seperator in this `literal`, so the recursion goes into a deeper and deeper level, and eventually results in call stack explosion :(
There are two kinds of solution to avoid this scenario:
1. force line breaks at the max position
2. just leave it as it is
I took the second solution, hope it may help others :)

Bugfix: fix call stack exceeded by long line without seperators

---

README.md
lib/index.js
package.json
test/data/index.js
test/index.js

Fixes https://github.com/Automattic/i18n-calypso/issues/39
This patch allows `i18n.setLocale()` to add new translations to the set of existing ones if the locale is not changed.
- Apply patch locally and [link](https://docs.npmjs.com/cli/link) `i18n-calypso` to your local directory
- Run `wp-calypso` locally with `npm start` and load localized page. Check that both https://widgets.wp.com/languages/notifications/fr.json and https://widgets.wp.com/languages/calypso/fr.json are now used
Note: also fixes https://github.com/Automattic/i18n-calypso/issues/27

Merge locale data with existing one when we're not switching locale

---

cli/preprocess-xgettextjs-match.js
test/cli/examples/i18n-test-examples.jsx
test/cli/index.js

A string like
```
i18n.translate( "This is how the test performed\u2026" );
```
would arrive in the POT file as 
```
msgid "This is how the test performed\u2026"
msgstr ""
```
Leading to an error message by `msgcat` like:
```
calypso-strings.pot:2:54: invalid control sequence
```
while the `\` should be escaped. This PR fixes this.

Fix improperly escaped control sequence in POT files

---

package.json

To test: Verify that this isn't actually used anywhere in the code.
Relevant for https://github.com/Automattic/wp-calypso/pull/19083

Remove react-addons-test-utils dependency

---

CHANGELOG.md
circle.yml
lib/localize/index.js
package.json
test/localize.js

The reason for this PR is to unblock wp-calypso from [upgrading to React 16](https://github.com/Automattic/wp-calypso/pull/19083)
This PR introduces a few changes:
1. removes usage of `React.createClass` from the HoC localize func and also from the HoC tests
2. update peer dep to allow React 16
3. bump minor version. this should be fully back-compat
Thoughts on next steps:
1. release a `v2.0.0` with the mixin removed

createClass --> es6 class

---

CHANGELOG.md
lib/localize/index.js
package.json

This PR makes it so that `i18n-calypso` can be used without any transpilation. `class` was introduced in https://github.com/Automattic/i18n-calypso/pull/43  which would mean the consumer would need to compile the js if targeting platforms below es6.
This pull request maintains compatibility with React 16 and below by use `create-react-class` instead of React.createClass or es6 class.
The other two solutions considered were:
1. es5 classes
2. build step within `i18n-calypso`
To Test
-----
1. go to `wp-calypso` 
2. run: `npm install Automattic/i18n-calypso#fix/es5-compat` to install this branch
3. run `CALYPSO_ENV=production NODE_ENV=production npm run build` and ensure minification succeeds

Use react-create-class for es5 compat

---

CHANGELOG.md
package.json

Also bump version, Changelog
See https://github.com/Automattic/interpolate-components/pull/12.
To Test
------

Bump `interpolate-components` to 1.1.1 (for React 16 compat)

---

package.json

This way babylon can be updated in downstream projects.

Allow newer versions of xgettext

---

CHANGELOG.md
package.json
test/index.js
test/localize.js
test/mixin.js

While preparing 1.8.5 (to include #46), I've discovered a number of failing tests. Could you please verify that my fixes are ok?
Most changes were required by the `enzyme` upgrade, which was in turn caused by this error message:
```
/home/ubuntu/i18n-calypso/node_modules/enzyme/build/react-compat.js:144
throw new Error('react-addons-test-utils is an implicit dependency in order to support react@0.13-14. ' + 'Please add the appropriate version to your devDependencies. ' + 'See https://github.com/airbnb/enzyme#installation');
```
The tricky thing here is that with `i18n-calypso` we want don't want to cut off older React versions, hence the `enzyme-adapter-react-helper` dance.

Fix tests for 1.8.5

---

lib/index.js

Instead of creating an object with all variants and then throwing away all but one
of them, use a more efficient switch statement. Should deliver some speedup of a
function that's called thousands of times.

Optimize the getJedArgs function

---

CHANGELOG.md
README.md
lib/index.js
package.json

This adds support for compressed jed as defined in D10012-code. The `key-hash` in the header specifies a hash algorithm (currently only sha1 supported) and it's length, so `sha1-4` would mean that only the first 4 characters of the hex representation of the original string should be used for lookup.

Add support for key hashing

---

CHANGELOG.md
lib/index.js
package.json

This fixes a problem where trying to use i18n-calypso as a module in a built application would result in an `i is undefined` fatal error.
Fixes https://github.com/Automattic/jetpack/issues/9020

Fixed undefined iterator.

---

circle.yml

Just a small PR to update circle CI to v2 configuration (v1 is deprecated).
> This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0.
Mostly stolen from #53.

Update: CircleCI v2 configuration

---

lib/index.js
test/index.js

This hotfixes the problem from https://github.com/Automattic/wp-calypso/issues/24674
…but also in general makes this function more bullet-proof as it's not considered very safe calling `JSON.stringify` on untrused data without a try/catch block.

Safe JSON stringification for cache key

---

circle.yml

We're migrating to Node 10 across several other codebases primarily
because it includes a more up-to-date and reliable npm version.
Node 10 will become the next LTS version.
Leverage `npm cit` shortcut that is essentially:
- npm ci (install packages) && npm t (test)

Update CI image to node:10 and use npm cit

---

cli/index.js

Add exportDefaultFrom, exportNamespaceFrom, and dynamicImport.

Update the parse options to support what calypso uses

---

lib/index.js
package-lock.json
package.json
test/index.js

`hash.js`, using just `sha1` is 2.3k gzipped, while `sha1` is 8k. 
Switch to save some bytes and align with what calypso uses.

Switch to hash.js from sha1

---

package-lock.json
package.json

Open up the range a bit so that downstream folks can resolve the moment-timezone they want on the 0.5 line. This is currently conflicting with the moment-timezone in Gutenberg, which is spec'd to `^0.5.16`.

Make the moment-timezone version less restrictive

---

CHANGELOG.md
package.json

Updating patch number and changelog.
In #77 we merged an important change to the `localize` props, which allows us to inform wrapped PureComponents of a locale switch.

Prep for 2.0.2 release
